import {
  FaReact,
  FaNodeJs,
  FaCss3Alt,
  FaHtml5,
  FaGithub,
  FaJsSquare,
} from "react-icons/fa";
import {
  SiTailwindcss,
  SiMysql,
  SiExpress,
  SiAxios,
  SiNextdotjs,
  SiPostgresql,
} from "react-icons/si";

export const techStack = [
  {
    id: 1,
    icon: FaReact,
    title: "React",
    color: "text-cyan-400",
    url: "https://react.dev",
  },
  {
    id: 2,
    icon: SiTailwindcss,
    title: "Tailwind CSS",
    color: "text-teal-400",
    url: "https://tailwindcss.com",
  },
  {
    id: 3,
    icon: FaNodeJs,
    title: "Node.js",
    color: "text-green-500",
    url: "https://nodejs.org",
  },
  {
    id: 4,
    icon: SiExpress,
    title: "Express",
    color: "text-gray-700 dark:text-gray-100",
    url: "https://expressjs.com",
  },
  {
    id: 5,
    icon: SiMysql,
    title: "MySQL",
    color: "text-yellow-300",
    url: "https://www.mysql.com",
  },
  {
    id: 6,
    icon: SiAxios,
    title: "Axios",
    color: "text-cyan-300",
    url: "https://axios-http.com",
  },
  {
    id: 7,
    icon: FaHtml5,
    title: "HTML5",
    color: "text-orange-500",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    id: 8,
    icon: FaCss3Alt,
    title: "CSS3",
    color: "text-blue-400",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  {
    id: 9,
    icon: FaGithub,
    title: "GitHub",
    color: "text-gray dark:text-white",
    url: "https://github.com",
  },
  {
    id: 10,
    icon: SiNextdotjs,
    title: "Next.js",
    color: "text-black dark:text-white",
    url: "https://nextjs.org",
  },
  {
    id: 11,
    icon: SiPostgresql,
    title: "PostgreSQL",
    color: "text-blue-700",
    url: "https://www.postgresql.org",
  },
  {
    id: 12,
    icon: FaJsSquare,
    title: "JavaScript",
    color: "text-yellow-400",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
];
